---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applause
  namespace: demo
  labels:
    app: applause
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: applause
  template:
    metadata:
      labels:
        app: applause
    spec:
      containers:
      - name: applause
        image: sh777/applause:1.0.8
        ports:
        - containerPort: 80


