apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: busybox
  namespace: demo
spec:
  serviceName: "busybox"
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - sleep
          - "3600"
      restartPolicy: Always


